### ISSUE TITLE
Panic on serving request: "slice of bounds out of range" in http.serve

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#145]
It happens regularly.

```
2015/10/23 22:39:33 http: panic serving 127.0.0.1:55793: runtime error: slice bounds out of range
goroutine 139376 [running]:
net/http.(*conn).serve.func1(0xc8fb3d4210, 0x7fe510fb46d8, 0xc8e02180c8)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
io.copyBuffer(0x7fe510ff1b88, 0xc9614706e0, 0x7fe510fb7298, 0xc961471820, 0xc877138000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:383 +0x3ba
io.Copy(0x7fe510ff1b88, 0xc9614706e0, 0x7fe510fb7298, 0xc961471820, 0xc961471820, 0x0, 0x0)
        /usr/local/go/src/io/io.go:351 +0x64
github.com/ironsmile/nedomi/handler/cache.(*reqHandler).lazilyRespond(0xc96b1304c0, 0xa942c6, 0x1099c5e)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/cache/handler_helpers.go:218 +0x64c
github.com/ironsmile/nedomi/handler/cache.(*reqHandler).knownRanged(0xc96b1304c0)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/cache/handler.go:127 +0x482
github.com/ironsmile/nedomi/handler/cache.(*reqHandler).handle(0xc96b1304c0)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/cache/handler.go:76 +0xf78
github.com/ironsmile/nedomi/handler/cache.(*CachingProxy).RequestHandle(0xc8203b4020, 0x7fe510faaa40, 0xc820193260, 0x7fe513036678, 0xc9614706c0, 0xc8d949f0a0)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/cache/caching_proxy.go:44 +0x224
github.com/ironsmile/nedomi/handler/flv.New.func1(0x7fe510faaa40, 0xc820193260, 0x7fe5130363b0, 0xc96b15af90, 0xc8d949f0a0)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/flv/flv.go:29 +0x330
github.com/ironsmile/nedomi/types.RequestHandlerFunc.RequestHandle(0xc8203b4040, 0x7fe510faaa40, 0xc820193260, 0x7fe5130363b0, 0xc96b15af90, 0xc8d949f0a0)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/types/request_handler.go:25 +0x4e
github.com/ironsmile/nedomi/handler/headers.(*Headers).RequestHandle(0xc8206ec6c0, 0x7fe510faaa40, 0xc820193260, 0x7fe5130363b0, 0xc96b15af90, 0xc8d949f0a0)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/headers/headers.go:37 +0x17b
github.com/ironsmile/nedomi/handler/headers.(*Headers).RequestHandle(0xc8206ec720, 0x7fe510faaa40, 0xc820193260, 0x7fe510fb48c8, 0xc9614705e0, 0xc8d949f0a0)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/headers/headers.go:37 +0x17b
github.com/ironsmile/nedomi/app.loggingHandler.func1(0x7fe510faaa40, 0xc820193260, 0x7fe510fb4858, 0xc8fb3d4c60, 0xc8d949f0a0)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/app/init.go:323 +0x20f
github.com/ironsmile/nedomi/types.RequestHandlerFunc.RequestHandle(0xc82000bf50, 0x7fe510faaa40, 0xc820193260, 0x7fe510fb4858, 0xc8fb3d4c60, 0xc8d949f0a0)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/types/request_handler.go:25 +0x4e
github.com/ironsmile/nedomi/app.(*Application).ServeHTTP(0xc820190100, 0x7fe510fb4858, 0xc8fb3d4c60, 0xc8d949f0a0)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/app/net.go:42 +0x13e
net/http.serverHandler.ServeHTTP(0xc8203f0000, 0x7fe510fb4858, 0xc8fb3d4c60, 0xc8d949f0a0)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8fb3d4210)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by ironsmile** [comment]
I believe that commits in the [readerFixes branch](https://github.com/ironsmile/nedomi/commits/readerFixes) does fix the problem. I haven't seen any of the panics since trying it out.
