### ISSUE TITLE
crash: makeslice: cap out of range in BreakInIndexes

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#170]
The following crash is observed in v0.1.4 of nedomi:

```
2015/11/10 03:41:40 http: panic serving 127.0.0.1:34059: runtime error: makeslice: cap out of range
goroutine 3497404 [running]:
net/http.(*conn).serve.func1(0xc8237ba2c0, 0x7f668c1ab260, 0xc820773820)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/ironsmile/nedomi/utils.BreakInIndexes(0xc8202b13c0, 0x0, 0xffffffffffffffff, 0x400000, 0x0, 0x0, 0x0)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/utils/indexes.go:12 +0x87
github.com/ironsmile/nedomi/handler/cache.(*reqHandler).lazilyRespond(0xc8202b1400, 0x0, 0xffffffffffffffff)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/cache/handler_helpers.go:199 +0x9f
github.com/ironsmile/nedomi/handler/cache.(*reqHandler).knownFull(0xc8202b1400)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/cache/handler.go:143 +0x1bd
github.com/ironsmile/nedomi/handler/cache.(*reqHandler).handle(0xc8202b1400)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/cache/handler.go:78 +0x10a8
github.com/ironsmile/nedomi/handler/cache.(*CachingProxy).RequestHandle(0xc82065e100, 0x7f668db3b798, 0xc8204af200, 0x7f668c1ab4d0, 0xc825c9bf50, 0xc848385880)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/cache/caching_proxy.go:44 +0x224
github.com/ironsmile/nedomi/handler/headers.(*Headers).RequestHandle(0xc8200d8b40, 0x7f668db3b798, 0xc8204af200, 0x7f668c1ab4d0, 0xc825c9bf50, 0xc848385880)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/headers/headers.go:37 +0x17b
github.com/ironsmile/nedomi/handler/headers.(*Headers).RequestHandle(0xc8200d8ba0, 0x7f668db3b798, 0xc8204af200, 0x7f668c1ab498, 0xc820773980, 0xc848385880)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/handler/headers/headers.go:37 +0x17b
github.com/ironsmile/nedomi/app.loggingHandler.func1(0x7f668db3b798, 0xc8204af200, 0x7f668c1ab3e0, 0xc8237ba9a0, 0xc848385880)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/app/init.go:322 +0x244
github.com/ironsmile/nedomi/types.RequestHandlerFunc.RequestHandle(0xc84839ac00, 0x7f668db3b798, 0xc8204af200, 0x7f668c1ab3e0, 0xc8237ba9a0, 0xc848385880)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/types/request_handler.go:25 +0x4e
github.com/ironsmile/nedomi/app.(*Application).ServeHTTP(0xc8200c2400, 0x7f668c1ab3e0, 0xc8237ba9a0, 0xc848385880)
        /root/tmp/gopath/src/github.com/ironsmile/nedomi/app/net.go:42 +0x13e
net/http.serverHandler.ServeHTTP(0xc820f3a960, 0x7f668c1ab3e0, 0xc8237ba9a0, 0xc848385880)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8237ba2c0)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by MStoykov** [comment]
given the fact that the `end` in BreakInIndexes is equal to 0xffffffffffffffff which looks like the max int value I would guess that an Object with Size 0 is cached ... which seems like the real issue.

 I would guess the upstream didn't return any size in a range request and we wrote 0 ?

**Comment by ironsmile** [comment]
This may be the case. But we should not be susceptible to crashes because something outside of our control is misbehaving.
